### PR TITLE
Preparing release 3.2.0

### PR DESCRIPTION
**Pull request by leplatrem**
* [x] Kinto upgrade
* [x] Wait for https://github.com/mozilla-services/kinto-amo/pull/22 
* [x] Update version and requirements

### CODE REVIEW

**Comment by Natim** [comment]
Shall we take this opportunity to also release kinto-signer with the autograph2 support?

**Comment by leplatrem** [comment]
> Shall we take this opportunity to also release kinto-signer with the autograph2 support?

Does it introduce breaking changes?

**Comment by Natim** [comment]
> Does it introduce breaking changes?

Nope, it just need to talk with autograph2 but it is already deployed in both prod and stage.

**Comment by leplatrem** [comment]
> Nope, it just need to talk with autograph2 but it is already deployed in both prod and stage.

Semantically it's a breaking change: a v2 instance has to run somewhere, and the configuration has to be changed to point to the specific autograph url.

I suggest we do it in two steps: 3.2.0 with the changes here. And a 4.0 with autograph v2.
What do you think?

**Comment by Natim** [comment]
I don't think we should release a 4.0 for this change.

**Comment by Natim** [comment]
However I would understand if you want to release a 3.2 without it and a 3.3 with only the Autograph 2 change.

**Pull request merged**
