### PR TITLE
Add checksums to dependencies (fixes #203)

### LINKED ISSUE #203: Add dependencies checksums

### PR DESCRIPTION
**Pull request by leplatrem**
Fixes #203  

I did that basically ``for l in `cat requirements.txt`; do hashin $l; done``

### CODE REVIEW

**Comment by leplatrem** [comment]
```
.venv/bin/pip install -Ue . -c requirements.txt
Obtaining file:///home/travis/gopath/src/github.com/mozilla-services/kinto-dist
The editable requirement file:///home/travis/gopath/src/github.com/mozilla-services/kinto-dist cannot be installed when requiring hashes, because there is no single file to hash.
make: *** [.venv/.install.stamp] Error 1
```

**Comment by peterbe** [comment]
Why `-e` and `-c` [here](https://github.com/mozilla-services/kinto-dist/blob/ebf32bccc562d8a5c826ebb21e548d75e71f73a4/Dockerfile#L25)? 
I think that needs to be replaced with a simple `pip install -r requirements.txt`.

**Comment by peterbe** [comment]
What is the goal? 

First it would be nice to get it to just pass with the existing CI stuff, i.e. Travis and Circle. Secondly, it would be nice to drop both and replace both with CircleCI 2.0. 

In Buildhub2 I went with *only* CircleCI 2.0 and all and everything in Docker. In fact, I used `docker-compose` and made two separate yaml files: [for local dev](https://github.com/mozilla/buildhub2/blob/master/docker-compose.yml) and [for CI](https://github.com/mozilla/buildhub2/blob/master/docker-compose.ci.yml).

Guide me and I can get involved and rubberduck fix this with you :)

**Comment by peterbe** [comment]
https://github.com/mozilla-services/kinto-dist/pull/214 is on its way.

**Pull request closed without merging**
