### PR TITLE
Prepare 5.0.0

### PR DESCRIPTION
**Pull request by glasserc**
This includes the migration and fix for the deleted_pkey race
condition.

### CODE REVIEW

**Comment by Natim** [comment]
If you are planning to make a release please also update the CHANGELOG and the setup.py

**Comment by glasserc** [comment]
What changes should I make to setup.py? I was trying to follow #159.. unless I should follow #158?

**Comment by leplatrem** [comment]
I wonder if we should bump this as a major, because of the migrate command to run.

Also, I think we should clarify how the migration progress should happen (eg. start with backoff of clients, migrate DB schema, upgrade Python app).

Also, what happens if the schema is migrated when the old Python app is still running? 
(As far as I can tell, tombstones will appear as records, no?)

**Comment by glasserc** [comment]
I've updated this PR to be more like #158, which prepares the release as well as upgrading a dependency. I've also included Kinto/kinto#1406, which definitively justifies bumping major on this one too :)

**Pull request merged**
