### PR TITLE
kinto-attachment 1.0 and amo2kinto 1.5.1

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Comment by glasserc** [comment]
Where is the amo2kinto dependency? I only see a change to kinto-attachment.

**Comment by Natim** [comment]
AFAIK It is a dependency of kinto-amo.

**Comment by glasserc** [comment]
Yes, I think I would peg the version of amo2kinto here, since this is the main entry point for production installs.

**Comment by glasserc** [comment]
r+

**Pull request merged**
