### PR TITLE
Prepare 22.0.0

### PR DESCRIPTION
**Pull request by leplatrem**

### CODE REVIEW

**Comment by leplatrem** [comment]
Unclear why it pulls the archive and not the Python 3.9 wheel:
``` 
Collecting canonicaljson-rs==0.3.0
  Downloading canonicaljson_rs-0.3.0.tar.gz (9.5 kB)
```
...plus I can't re-run jobs. Annoying.

**Comment by smarnach** [comment]
You should be able to rerun jobs in Circle once you log in with your Github account – the button is in the top right corner:

image

I'll review after lunch.

**Comment by leplatrem** [comment]
The Rerun options are grayed out, because I don't use my main account on CircleCI... 

Locally it seems to pick up the wheel correctly. I can't explain why it doesn't during the Docker build...

```
➜  /tmp virtualenv --python=python3.9 venv                                                                      
Running virtualenv with interpreter /usr/bin/python3.9
Already using interpreter /usr/bin/python3.9
Using base prefix '/usr'
New python executable in /tmp/venv/bin/python3.9
Also creating executable in /tmp/venv/bin/python
Installing setuptools, pip, wheel...
done.
➜  /tmp source venv/bin/activate
(venv) ➜  /tmp pip install canonicaljson-rs
Collecting canonicaljson-rs
  Downloading canonicaljson_rs-0.3.0-cp39-cp39-manylinux1_x86_64.whl (579 kB)
     |████▌                           | 81 kB 24 kB/s eta 0:00:21

```

**Comment by smarnach** [comment]
I get the same error locally. I can debug it on my machine, since I can reproduce it.

**Comment by smarnach** [comment]
It looks like this was just a missing hash. Weird that it worked for you locally.

**Comment by smarnach** [comment]
I see, you just tried it in a venv, without the hash constraints, so that explains it.

**Review by smarnach — APPROVED** [review]

**Comment by leplatrem** [comment]
Oh thanks Sven! 
I may have added the hash using Python 3.8, that may explain it!

**Comment by smarnach** [comment]
Let's roll this out on Monday – I don't want any trouble on the weekend.

**Comment by leplatrem** [comment]
> Let's roll this out on Monday – I don't want any trouble on the weekend.

Sure! Next Thursday is fine :)

**Comment by leplatrem** [comment]
bors merge

**Pull request merged**
