### PR TITLE
Upgrade Cornice to always return CORS headers

### PR DESCRIPTION
**Pull request by leplatrem**
Fix https://bugzilla.mozilla.org/show_bug.cgi?id=1683195

### CODE REVIEW

**Review by smarnach — APPROVED** [review]
We'll need to update the kinto.ini in production as well once this is deployed.

**Comment by smarnach** [comment]
The integration tests failed, but I couldn't figure out why in the 20 seconds I looked at them. I triggered a rerun for now. If that fails again, we can take a proper look.

**Comment by leplatrem** [comment]
It's broken on other PRs too :(

**Comment by leplatrem** [comment]
bors merge

**Pull request merged**
