### PR TITLE
Use ubuntu 18.04, fixes #224

### LINKED ISSUE #224: Use ubuntu 18.04
Once https://github.com/mozilla-services/kinto-dist/pull/214 lands we should see to use Ubuntu 18.04 in CircleCI. 

See https://blog.ubuntu.com/2018/07/09/minimal-ubuntu-released

> "On Dockerhub, the new Ubuntu 18.04 LTS image is now the new Minimal Ubuntu 18.04 image. Launching a Docker  instance with docker run ubuntu:18.04  therefore launches a Docker instance with the latest Minimal Ubuntu."

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Comment by peterbe** [comment]
Uh? Do we need >1 review approvals? "Merging is blocked".

**Comment by peterbe** [comment]
PS. I don't have admin access on this repo so I can't check the settings.

**Comment by glasserc** [comment]
It says "The target branch requires all commits to be signed. [Learn more about signing commits.](https://help.github.com/articles/about-gpg/)"

**Comment by peterbe** [comment]
Uh?! Why isn't my commit signed. What happened?! 
My other commits on [mozilla-services/tecken](https://github.com/mozilla-services/tecken/commits/master) are verified. /me stumped

**Comment by peterbe** [comment]
I'm a never-ending-noob when it comes to these kinds of things but a difference between say mozilla-services/tecken and mozilla-services/kinto-dist is that on tecken I push to my fork and use GitHub to merge into mozilla-services. With kinto-dist, I noticed that everyone pushed to this main repo to make PRs.

**Comment by peterbe** [comment]
@glasserc I don't know why my first commit wasn't signed. I wonder if it's because I made a commit before I had run `ssh-add` to start my key. Either way, I've rebased it now and now the 1 commit is signed.

**Pull request merged**
