### PR TITLE
Restore version fields signer and changes capabilities metadata

### PR DESCRIPTION
**Pull request by leplatrem**

### CODE REVIEW

**Comment by leplatrem** [comment]
This works only if kinto-dist is installed with `pip install -e .` which we don't do. We'd have to find another approach. Hard-coding?

**Comment by grahamalama** [comment]
> This works only if kinto-dist is installed with `pip install -e .` which we don't do. We'd have to find another approach. Hard-coding?

Maybe we should do this. It feels a little less hacky than manually adding `kinto_remote_settings` to the `PYTHONPATH`. Thoughts?

**Comment by grahamalama** [comment]
@leplatrem I rebased this branch on main to account for #1934. Since it included breaking changes, I [modified the changelog](https://github.com/mozilla-services/kinto-dist/pull/1944/files#diff-2c623f3c6a917be56c59d43279244996836262cb1e12d9d0786c9c49eef6b43c) so that we'll be releasing a new major version 27 for the next release, which will include the bugfixes that were addressed in this PR.

I also added a hardcoded version value as we discussed on our call today.

**Review by smarnach — APPROVED** [review]

**Comment by leplatrem** [comment]
Works for me.

I know it's only a temporary step, but we could still update the paragraph about releasing in the README

**Comment by grahamalama** [comment]
> Works for me.
> 
> I know it's only a temporary step, but we could still update the paragraph about releasing in the README

Good call https://github.com/mozilla-services/kinto-dist/pull/1944/commits/fad7aa9c020a3adad65906229b65c0825dec710d

**Comment by leplatrem** [comment]
r+

**Comment by grahamalama** [comment]
bors merge

**Pull request merged**
