### PR TITLE
Simple integration test

### LINKED ISSUE #27: Add simple integration tests
* signature
* attachment
* ...

### PR DESCRIPTION
**Pull request by leplatrem**
Fixes #27

### CODE REVIEW

**Comment by leplatrem** [comment]
Interesting:

```
"POST  /v1/buckets/e4c75c18-06cd-4511-40b6-3fe11d3386a8/collections/articles/records/abcde/attachment" 201 (16 ms) 'bucket_id' agent=curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3 authn_type=basicauth collection_id=record collection_timestamp=1468561044412 errno=110 exception=Traceback (most recent call last):

  File "/home/travis/gopath/src/github.com/mozilla-services/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween

    response = handler(request)

  File "/home/travis/gopath/src/github.com/mozilla-services/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween

    reraise(*exc_info)

  File "/home/travis/gopath/src/github.com/mozilla-services/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 90, in tm_tween

    manager.commit()

  File "/home/travis/gopath/src/github.com/mozilla-services/kinto-dist/.venv/local/lib/python2.7/site-packages/transaction/_manager.py", line 123, in commit

    return self.get().commit()

  File "/home/travis/gopath/src/github.com/mozilla-services/kinto-dist/.venv/local/lib/python2.7/site-packages/transaction/_transaction.py", line 265, in commit

    self._callBeforeCommitHooks()

  File "/home/travis/gopath/src/github.com/mozilla-services/kinto-dist/.venv/local/lib/python2.7/site-packages/transaction/_transaction.py", line 336, in _callBeforeCommitHooks

    hook(*args, **kws)

  File "/home/travis/gopath/src/github.com/mozilla-services/kinto-dist/.venv/local/lib/python2.7/site-packages/kinto/core/events.py", line 84, in _notify_resource_events_before

    request.registry.notify(event)

  File "/home/travis/gopath/src/github.com/mozilla-services/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid/registry.py", line 91, in notify

    [ _ for _ in self.subscribers(events, None) ]

  File "/home/travis/gopath/src/github.com/mozilla-services/kinto-dist/.venv/local/lib/python2.7/site-packages/zope/interface/registry.py", line 328, in subscribers

    return self.adapters.subscribers(objects, provided)

  File "/home/travis/gopath/src/github.com/mozilla-services/kinto-dist/.venv/local/lib/python2.7/site-packages/zope/interface/adapter.py", line 596, in subscribers

    subscription(*objects)

  File "/home/travis/gopath/src/github.com/mozilla-services/kinto-dist/.venv/local/lib/python2.7/site-packages/pyramid/config/adapters.py", line 130, in subscriber_wrapper

    return derived_subscriber(*arg)

  File "/home/travis/gopath/src/github.com/mozilla-services/kinto-dist/.venv/local/lib/python2.7/site-packages/kinto_signer/__init__.py", line 22, in on_collection_changed

    key = "/buckets/{bucket_id}/collections/{collection_id}".format(**payload)

KeyError: 'bucket_id' lang=None time=2016-07-15T05:37:24 uid=cbd3731f18c97ebe1d31d9846b5f1b95cf8eeeae586e201277263434041e99d1

curl: (22) The requested URL returned error: 500
```

**Comment by leplatrem** [comment]
* Crash was due to Kinto/kinto#704 (default bucket) fixed in kinto 3.3
* Added safety check in kinto-signer meanwhile https://github.com/Kinto/kinto-signer/pull/99
* Remove usage of default bucket in smoke test

**Comment by leplatrem** [comment]
Can now be reviewed / merged.

@Natim r?

**Comment by Natim** [comment]
r+

**Pull request merged**
