### PR TITLE
Add kinto-redis to requirements (fixes #653)

### LINKED ISSUE #653: Add kinto-redis to this repo
At @autrilla's request, to facilitate the move to GCP, which doesn't offer hosted Memcached.

### PR DESCRIPTION
**Pull request by leplatrem**
fixes #653

I don't know if we should enable it instead of Memcached... Maybe once every service running kinto-dist has moved to GCP?

### CODE REVIEW

**Comment by glasserc** [comment]
The tests fail because of a missing pin on a dependency. Also, on Vidyo it seemed like we agreed that we should write a test?

**Comment by leplatrem** [comment]
> Also, on Vidyo it seemed like we agreed that we should write a test?

Yes. I don't know what to do something simple though. Should I just replace memcached by redis?

**Comment by glasserc** [comment]
Yes, I think that would be good enough. We don't have exhaustive testing of the memcache integration/backend. I think the only thing we actually have is the heartbeat, which almost doesn't even count because of https://github.com/Kinto/kinto/issues/2107.

**Pull request merged**
